# Collaborators (including web sites where you got help: (enter none if you didn't need help)
#  none
personname= input("enter a person's name")
verb=input('enter a verb')
adverb=input('enter an adverb')
food=input('enter a food')
personname2=input("enter a person's name")
verb2=input('enter a verb')
adverb2=input('enter an adverb')
print (f"There once was a person named {personname} that really liked to {verb} {adverb}. One time, {personname} was eating a {food} and realized that {personname2} wanted to {verb2} \n with them. So {personname} and {personname2} {verb2}ed together {adverb2}")